### ISSUE TITLE
AGOL endpoint

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#1]
This would allow us to use the geocoding web api from arcgis online.

http://mapserv.utah.gov/arcgis/sdk/rest/index.html#/Geocode_Service/02ss0000003n000000/
http://mapserv.utah.gov/arcgis/sdk/rest/index.html#/Find_Address_Candidates/02ss00000015000000/

Find_Address_Candidates has a lot of parameters that we may not need. Maybe Michael can forward a link to an AGOL map that uses an address locator so that I can check out what parameters it uses?

**Comment by steveoh** [comment]
fixed in 1.6.0

**Comment by stdavis** [comment]
Are there any docs on how to use this functionality? Tom from DOGM is asking how to use our geocoder in AGOL web maps.

**Comment by steveoh** [comment]
No. This was a hack to make it work. https://github.com/agrc/api.mapserv.utah.gov/issues/49 Will make it work for others
