### ISSUE TITLE
space in desktop ip

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#103]
the application stored a space before the ip address causing issues. 

eg: ` 127.0.0.1`

Leading and trailing spaces should be trimmed.

**Comment by stdavis** [comment]
Is this just a front-end thing or are there some database cleanup or other backend fixes?

**Comment by steveoh** [comment]
The frontend should mark it as invalid. I guess the server should also reject it. It would be interesting to see how often this has occurred but the keys wouldn't work so folks aren't using them.
