### ISSUE TITLE
localhost/dev keys returning 400s

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#109]
My requests using localhost/dev keys have started returning:
```
{"status":400,"message":"Invalid API key."}
```

Request headers:
```
GET /api/v1/Geocode/3988%20s%201925%20e/84124?apiKey=<my key>&spatialReference=3857 HTTP/1.1
Host: api.mapserv.utah.gov
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Accept: */*
Origin: http://localhost:8000
Referer: http://localhost:8000/src/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,es;q=0.8
```

Did Chrome break something?

**Comment by steveoh** [comment]
I'm not sure that the api logic allows custom ports. There aren't [any tests for it](https://github.com/agrc/api.mapserv.utah.gov/blob/master/WebAPI.API.Tests/Handlers/AuthorizationHandlerTests.cs)

**Comment by stdavis** [comment]
We should support them. I wonder what happened to break them? I've used them for years and I don't think that they are uncommon in development.

**Comment by stdavis** [comment]
A newly generating key worked. ¯\_(ツ)_/¯
