### ISSUE TITLE
Unexpected no match result for 514 E 3825 N, 84414

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#115]
From @geekcyclist working with Vista addresses:
>The geocoder does not find a matching address at even the default score of 70. That address actually returns the X/Y for the centerline for 558 E 3825 N at a score of 68.
>Clerk says "that parcel was assigned a new address in 2018 via our Recorders Office and it appears on their mapping"
>The old address was 3792 N 475 E
>So they "bent" the address around the corner for this parcel.

Here's a reproduction of the issue: [http://api.mapserv.utah.gov/api/v1/geocode/514 E 3825 N/84414?acceptScore=65&apiKey=AGRC-Dev](http://api.mapserv.utah.gov/api/v1/geocode/514%20E%203825%20N/84414?acceptScore=65&apiKey=AGRC-Dev)

Looks like we may be missing some centerline and possibly address point data from Weber County. Here's a screenshot from atlas:
![image](https://user-images.githubusercontent.com/1326248/90292120-86418180-de3e-11ea-8912-b89fe725530e.png)

cc @gregbunce

**Comment by steveoh** [comment]
@ZachBeck is there an address point at that location?

**Comment by ZachBeck** [comment]
We don't have a point for that location, I'll check with the county.

**Comment by ZachBeck** [comment]
This slipped through the cracks on my end, I just contacted the county. @gregbunce it looks like the roads need updating in this area as well,

**Comment by steveoh** [comment]
/remind @ZachBeck and @gregbunce to check this out again next week 8/31

**Comment by ZachBeck** [comment]
The county responded and said they would fix the address point.

**Comment by steveoh** [comment]
> The county responded and said they would fix the address point.

That is great. When do you expect the data to flow into the SGID?

**Comment by ZachBeck** [comment]
Weber sent Michael an update yesterday so hopefully it shows up next month in the points. The fixes for the roads are in the county's data now.

**Comment by steveoh** [comment]
@gregbunce when do you expect the data to flow into the SGID so I can update the reminder

**Comment by gregbunce** [comment]
i'll fix the roads and it will be reflected in this Thursday's sgid road update.  The public will see it on Friday.

**Comment by steveoh** [comment]
ok so to recap, 

- roads will be updated Thursday and the SGID flow will get that to the api by next week.
- address points are sometime in September hopefully?

@ZachBeck do you have a better guess on the address points now or will you need more time to make an estimate?

**Comment by ZachBeck** [comment]
No, it will still happen when they give Michael updates in September.

**Comment by steveoh** [comment]
/remind me to geocode the address on 9/7

**Comment by gregbunce** [comment]
the road segment has been updated/extended in utrans to incorporate 514 E 3825 N, 84414 (as well as the other addresses on the block). again, the data will be public this Friday. 
![image](https://user-images.githubusercontent.com/16906316/91777393-ecebcc80-ebac-11ea-8662-07a5270d66d3.png)

**Comment by steveoh** [comment]
@gregbunce The geocoding endpoint is returning the same result. Is that related to the issues mentioned in the blog post? Has the road grinder gdb not get updated?

**Comment by steveoh** [comment]
It seems the 🚜 pallet did not deploy the streets locator. I'll look into it. I pushed the updated locator manually and the result score is 100 now. Go team.
