### ISSUE TITLE
Add version support for v2 api explorer

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#121]
The v2 API explorer needs to be able to support the v1 and v2 APIs. This could be done via the URL. For example:
- `/documentation/v1/geocoding`
- `/documentation/v2/geocoding`

This means that we would maintain two separate sets of endpoint components; one for each version.

New react-router routes would need to be added for each version.

@steveoh Does this sound like the right direction to you?

**Comment by steveoh** [comment]
I think the router routes sound like the right direction. I would try to reuse the endpoint components as much as possible with possible v1 or v2 annotations to show and hide different fields or information. Does that sound possible? Otherwise we will have a lot of duplicated code.

**Comment by stdavis** [comment]
That's an interesting idea. I feel like that it technically possible. I'm not familiar enough with the differences between v1 and v2 to know if it would work. But it sounds like they are pretty similar.
