### ISSUE TITLE
Deep links for API Explorer

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#122]
All headers in the api explorer documentation should be deep-linkable. For example:

- `/documentation/v1/geocoding/docs/#acceptScore`

This would require adding a new react-router route for displaying the demo vs. the documentation components.

@steveoh Is this what you were thinking?

**Comment by steveoh** [comment]
Sounds reasonable.

**Comment by stdavis** [comment]
This is doable now in the starlight outline on the right side of the page.
