### ISSUE TITLE
New user registration redirects back to login screen instead of new profile page

### ISSUE THREAD

**Issue by maxxpm-ben** [agrc/api.mapserv.utah.gov#144]
This isn't technically an issue with the API, but I couldn't find another contact method. I have tried several times to register for an account to get an API key, but nothing happens when I click register.

**Comment by steveoh** [comment]
To clarify, you are clicking on register here? 

https://developer.mapserv.utah.gov/AccountAccess
![image](https://user-images.githubusercontent.com/325813/144888130-8fcae7ba-1fa2-4c72-8d73-9e2855b02ce5.png)

**Comment by maxxpm-ben** [comment]
Yes

**Comment by steveoh** [comment]
I just tried this and yes, something is out of the ordinary. It redirected my back to the login screen. The account was created so try to login with the credentials you supplied first.

**Comment by steveoh** [comment]
Did you get the account confirmation email?

**Comment by maxxpm-ben** [comment]
No, I did not.

**Comment by steveoh** [comment]
Would you send me an email from the account you signed up with to sgourley@utah.gov please please.

**Comment by steveoh** [comment]
will you try to create an account again or would you be ok if I tried for you?

**Comment by maxxpm-ben** [comment]
I just tried, and it didn't work. Feel free to try it for me.

**Comment by steveoh** [comment]
I just tried to register you and I now see an account in the db. Did you get an account confirmation email?

**Comment by maxxpm-ben** [comment]
Yes, but I just tried to login with the credentials I created, and I was redirected back to the login screen.

**Comment by steveoh** [comment]
Use the credentials I provided for you in your email.

**Comment by steveoh** [comment]
This bit of code does not appear to be doing what it is supposed to. https://github.com/agrc/api.mapserv.utah.gov/blob/5b975b147cd37d53c6427faf38ac076f20494dc2/WebAPI.Dashboard/Controllers/AccountAccessController.cs#L137-L150

**Comment by steveoh** [comment]
It seems that updating the database has solved this issue.
