### ISSUE TITLE
API Key Invalid

### ISSUE THREAD

**Issue by mw-lcsd** [agrc/api.mapserv.utah.gov#150]
Hi,

I am trying to write a python script to geocode addresses using the UGRC Web API. I have created a Desktop Application key and am using that key in my python script. However, whenever I run the script, it fails with a message of "Invalid API Key".

I'm not sure what I am doing wrong. Any help would be appreciated!

**Comment by mw-lcsd** [comment]
Never mind. Problem solved.

**Comment by steveoh** [comment]
What was the issue if you don't mind me asking?
