### ISSUE TITLE
[request] Return city and/or zip for reverse geocoding

### ISSUE THREAD

**Issue by jacobdadams** [agrc/api.mapserv.utah.gov#201]
Glenn Fishbourne/Breaking Point Solutions requested being able to get city or zip from the reverse geocode (currently just returns an address, unless we're both missing something in the docs).

**Comment by steveoh** [comment]
Nope, you are not missing anything from the docs. The solution would be to make a search request for the zip or city with the input coordinates. I'll look into accessing attributes from a reverse geocode request.
