### ISSUE TITLE
Addresses with Suites

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#22]
sterlingpetersen@utah.gov

> I've run across something that might be a small bug in the geocoding API. I didn't do thorough testing, but it appears that if a suite number on an address contains an alpha character, the geocoding fails:

```html
http://api.mapserv.utah.gov/api/v1/geocode/1151 E 3900 S Ste B150/84107?spatialReference=4326&pobox=true&apiKey=AGRC-ApiExplorer
```
vs.

```html
http://api.mapserv.utah.gov/api/v1/geocode/1151 E 3900 S Ste 150/84107?spatialReference=4326&pobox=true&apiKey=AGRC-ApiExplorer
```

**Comment by steveoh** [comment]
this is fixed but not deployed yet. I had to update the assumptions on how secondary addresses are designed.

**Comment by steveoh** [comment]
deployed.

**Comment by sterlingpetersen** [comment]
This address with a suite number fails:

http://api.mapserv.utah.gov/api/v1/geocode/1490%20E%20FOREMASTER%20DR%20STE%20150/SAINT%20GEORGE?apiKey=

Works without the suite:

http://api.mapserv.utah.gov/api/v1/geocode/1490%20E%20FOREMASTER%20DR/SAINT%20GEORGE?apiKey=

**Comment by steveoh** [comment]
Thanks for the report. Ill have to check what is up a little close next week. I would assume this should work because we check for suites https://github.com/agrc/api.mapserv.utah.gov/blob/master/WebAPI.API/App_Start/CacheConfig.cs#L184
