### ISSUE TITLE
SGID93 on 112

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#24]
@MichaelAGRC just told me that the server that this project is on is trying to hit SGID93 on 112. I assume that this project is the one doing that but not positive.

**Comment by steveoh** [comment]
the web api does not run on 112. let's go :fishing_pole_and_fish:

**Comment by steveoh** [comment]
michael clarified.

**Comment by steveoh** [comment]
I think this has been resolved. We an reopen if not.
