### ISSUE TITLE
Route Milepost Output Spatial Reference

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#25]
I get

```
{
Message: "An error has occurred."
}
```

returned from this request: http://api.mapserv.utah.gov/api/v1/geocode/milepost/15/5?spatialReference=3857&apiKey=AGRC-ApiExplorer

It returns successfully when I remove the `spatialReference` parameter.

**Comment by steveoh** [comment]
i believe this is fixed. Please verify and act.

**Comment by stdavis** [comment]
Looks good! Thanks.
