### ISSUE TITLE
Reverse Geocode with spatialReference 3857 yields no results

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#26]
When I submit a point in web mercator to the reverse geocode service I get no results.

For example: 
x: -12449589.63970003
y: 4965953.392828723
distance=50
spatialReference=3857

yields

```json
{"result":{},"status":200}
```

whereas the same point in utm works:

x: 429309
y: 4504098
distance: 50
spatialReference: 26912

```json
{"result":{"inputLocation":{"x":429309.47224767046,"y":4504099.0752038416},"address":{"street":"4002 S 1925 E"}},"status":200}
```

**Comment by steveoh** [comment]
Good catch. 

I am sending the wkid (3857) to the locator, but the locator is still expecting the input location to be 26912.

**Comment by stdavis** [comment]
Thanks!
