### ISSUE TITLE
Resolve Point vs. Pointe

### ISSUE THREAD

**Issue by sterlingpetersen** [agrc/api.mapserv.utah.gov#27]
This address fails to geocode, because the street name lacks the 'e' at the end: point vs. pointe.

Fails:
http://api.mapserv.utah.gov/api/v1/geocode/5974%20FASHION%20POINT%20DR/84403?apiKey=

Works:
http://api.mapserv.utah.gov/api/v1/geocode/5974%20FASHION%20POINTE%20DR/84403?apiKey=

This issue pops up about 30 times in Utah [NPPES](http://download.cms.gov/nppes/NPI_Files.html) addresses, but as far as I can see, only for this particular street. Most addresses in NPPES seem to use 'point' without an 'e'.

Not sure if this is something that should be solved server-side, client-side, or in the underlying data. Google seems to have the street name listed as 'point', by the way.

**Comment by sterlingpetersen** [comment]
Similar issue with 'twn' and 'twne':

Fails:
http://api.mapserv.utah.gov/api/v1/geocode/1551%20S%20RENAISSANCE%20TWN%20DR%20SUITE%20420/Bountiful?apiKey=

Works:
http://api.mapserv.utah.gov/api/v1/geocode/1551%20S%20RENAISSANCE%20TWNE%20DR%20SUITE%20420/Bountiful?apiKey=

**Comment by steveoh** [comment]
I think these issues boil down to our base address data. We have "FASHION POINTE" and "RENAISSANCE TOWNE" as the street names for these. That is why they are not found and why the misspelling costs so much with the geocode score. We are not modifying the abbreviations in street name values. We are only expanding road types and removing unit types. 

I can ask @gregbunce to validate that these road names are correct with the counties/cities. I don't think we will make any code changes.

**Comment by gregbunce** [comment]
Yes, there does seem to be some discrepancy between Google and Weber County's data.  I checked Weber's data for points (address) and streets and both datasets use "Pointe" in the name.  In this situation, I'm inclined to stick with Weber County's data and advise you to use "Pointe" when geocoding addresses on this street segment.
Also, as far as Renaissance.. the City of Bountiful uses "Towne" in both their street and address point datasets.  Again, I would stick with "TWNE" when geocoding addresses on this segment.
