### ISSUE TITLE
attributeStyle option for search method is missing in api explorer

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#28]
http://api.mapserv.utah.gov/#search

Here's what I have in the [`WebAPI.js` docs](https://github.com/agrc/agrc.widgets/blob/de07d1cc00d27e08fc905d0062f5a023a05905a4/modules/WebAPI.js#L71-L78):

```
// options.attributeStyle: String (defaults to 'identical')
            //      Controls the casing of the attributes that are returned.
            //      Options:
            //
            //      'identical': as is in data.
            //      'upper': upper cases all attribute names.
            //      'lower': lowercases all attribute names.
            //      'camel': camel cases all attribute names 
```

**Comment by steveoh** [comment]
We chose to leave this undocumented since in version two identical is going to be the default option. We introduced these other options because camel case, the default, was messing up on acronyms.
