### ISSUE TITLE
Self-service link to docs is broken

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#280]
This link is broken. I also noticed that it goes to a hosted base URL in dev. Maybe it could be fixed to link to the dev version?

![Image](https://github.com/agrc/api.mapserv.utah.gov/assets/1326248/8b935e1c-03cc-4890-a1b3-2a37b7cd8c62)

**Comment by steveoh** [comment]
should be /docs instead of /en/documentation
