### ISSUE TITLE
Create shared service account for UGRC app keys

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#307]
We learned today that we can apply for a security exception (525 form) to create a shared UtahID account. The credentials can then be shared among our group. It was unclear if we could set one up with the same email as an existing Google Group (such as ugrc-developers@utah.gov) so that the 2FA token could be sent via email. This will allow us to create and manage keys that are not tied to our individual accounts.

Related issues: #21

**Comment by steveoh** [comment]
RITM0404423

**Comment by steveoh** [comment]
Our exception has been approved. awaiting fulfillment.

**Comment by steveoh** [comment]
We are going to use a shared account we already have, since they cost $$, and work with @MichaelAGRC to automagically forward mail to our google group.
