### ISSUE TITLE
Notify all users of account changes

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#308]
When we have a production deployment date idea, we should blog and then send out a marketing email describing the change to all the web api users and the steps required to claim old account keys.

**Comment by steveoh** [comment]
test email sent. awaiting feedback

**Comment by nathankota** [comment]
- **Suggestion:** Change to _Important updates to UGRC API accounts_
  > Important updates for the UGRC API accounts

- **Question:** Provide link for [UtahID identity system](https://dts.utah.gov/what-we-are-doing/our-initiatives/security-and-access-management/)?

- **Suggestion:** Slight verbiage change to _Simultaneously with the migration to UtahID, the UGRC API landing page [link] and self service websites [link]..._

  > At the same time the API landing page and self service websites are being relaunched...

- **Suggestion:** Slight verbiage change to _Eventually, in an effort to tidy up,..._
  > After some time in an effort to tidy up, all API keys...

**Comment by steveoh** [comment]
comments incorporated. thanks!

**Comment by steveoh** [comment]
When do we want to send this out?

**Comment by steveoh** [comment]
Scheduled the send of this for 7/8
