### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#31]
Would it be possible to create a docker container for this project? I'd like to get my hands dirty and give #30 a try. Wondering if it's worth trying to set up this on my VM or if docker would be feasible.

**Comment by steveoh** [comment]
I think they're is an aspnet 5 container. You might be able to make it happen. That'd be pretty awesome.

**Comment by steveoh** [comment]
I don't think we are going to containerize this project. we are actively working on an aspnet core port of this project and that will be containerized. I am going to close this as it is possible to use containers with the next version of this project.
