### ISSUE TITLE
create onboarding email automation

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#322]
A 3 email series email introducing folks to the api, the resources for the api, and other ugrc services.

### todo

- [ ] Add link to blog post from #308

**Comment by steveoh** [comment]
The emails and list have been created. We need to hash out the final content but it's at a pretty good place now.

**Comment by nathankota** [comment]
## Email: Test - UGRC API Welcome Kit
#### Notes
It reads well and the content looks good to me other than the logo not appearing on the test email I received.

![image](https://github.com/agrc/api.mapserv.utah.gov/assets/15659642/1fc67043-99b8-4b35-b2fe-3739839aa0fb)

## Email: Test - UGRC API Welcome Kit follow up
#### Notes
- Also reads well. 
- Broken link: [sample code](https://github.com/agrc/api.mapserv.utah.gov/tree/main/samples)
- Broken link: [OpenAPI spec](https://api.mapserv.utah.gov/openapi/v1/api.json)
- Nitpick: align with the final email by hyphenating _locally-sourced_. This could also be done for _custom-designed_, but not critical.

> In our final email we will share other relevant UGRC services that can compliment your spatial data and GIS needs including **locally sourced** and custom designed base maps...

- Fix: change "compliment" to "complement"
 > In our final email we will share other relevant UGRC services that can **compliment**...

## Email: Test - UGRC API Welcome Kit final email
#### Notes
- ❤️ the call out to other tools and services
- Content and verbiage are good
- Future: eventually include link(s) to vector tile base maps
- Nitpick: add comma after _locally-sourced_ in the sentence:

> Enjoy the locally-sourced authoritative data...
- Add links to [GitHub issue](https://github.com/agrc/api.mapserv.utah.gov/issues/new) or [contacting the DTS Help Desk](https://services.dts.utah.gov/), like in the second email.

**Comment by steveoh** [comment]
1. I deleted and created a new image as it was far too large. New emails should have the correct one.
1. The sample code link will work once dev is merged to main.
1. The OpenAPI link will work once the domain is migrated to the cloud service.
2. added hyphens
3. Fixed the spelling
4. added a comma
5. fixed the links

I'm happy to call this done unless anyone else who got the emails wants to suggest any changes. Feel free to reopen the issue.
