### ISSUE TITLE
Spatial reference parameter in search does not appear to be working

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#363]
Lee Eschler pointed this out:

https://api.mapserv.utah.gov/api/v1/search/cadastre.davis_county_parcels/parcel_id,parcel_add,parcel_city,parcel_zip,parcelscur,parcelnotes,shape?spatialReference=4326&predicate=UPPER(parcel_id)%20%3D%20UPPER(%27030680007%27)&attributeStyle=identical&apiKey=AGRC-dev

This is returning 26912 despite passing 4326.

**Comment by steveoh** [comment]
@stdavis I believe this is intended. Shape is a source data attribute, which is 26912, where the shape@ is the token that gets projected by the api.

I want to say this is [how the old code functioned](https://github.com/agrc/api.mapserv.utah.gov/blob/legacy/gcve/WebAPI.API/Controllers/API/Version1/SearchController.cs#L147-L247). Did Lee notice an unexpected change?

**Comment by stdavis** [comment]
From someone in Lee's office:
>This is an existing application that we were notified wasn't working yesterday. So I assume something broke when the new system was deployed.

I would have thought that the spatial reference parameter would have affected the shape column. Would it be a breaking change to just upgrade `shape` to `shape@`?

**Comment by steveoh** [comment]
I thought shape was stripped from the old api but I can double check. 

It would be a breaking change to update that yes.
