### ISSUE TITLE
What's the offset for /geocode/multiple

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#37]
I had someone ask me this question and I didn't find it right away in the code. We should probably add it to the docs as well.

**Comment by steveoh** [comment]
It's 10 meters I think for the centerline as it is a locater property. It should be in the wiki under offset.

**Comment by stdavis** [comment]
Looks like it's 15...
![image](https://cloud.githubusercontent.com/assets/1326248/20397094/b1897c4a-aca5-11e6-8759-27fbbcbea78e.png)
