### ISSUE TITLE
Add bounding box as a geometry option for the search service

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#42]
Currently the `geometry` parameter supports only points. Expand this to support bounding boxes and possibly polygons.

There should be some way to prevent users from making requests that would overwhelm the server. I would suggest a feature limit (with some sort of warning in the returned data) rather than a limit on area (which is dependent upon the distribution of the data being queried).

**Comment by steveoh** [comment]
@rschoenefeld will you test this out and let me know how it goes for you?
