### ISSUE TITLE
Issue with some Street Types on API geocoder requests

### ISSUE THREAD

**Issue by gregbunce** [agrc/api.mapserv.utah.gov#44]
I'm not sure that this is an across-the-board issue but for the below-stated addresses, they will not code when supplying the street type.  If you remove the street type they code, but when you look at the segment/point they matched on that segment/point contains the street type.
- 9211 N Pebble Creek Loop, Eagle Mountain 84005
- 5811 W Park West Rd, Provo 84003

**Comment by steveoh** [comment]
Both addresses geocode with the native locators in arcgis server. This is an issue in the api.

**Comment by steveoh** [comment]
I think if the direction is before the street type and the value before the direction is non numeric then we can assume that it is a part of the street name and not a suffix direction.

These addresses are also affected and will be good test case candidates. 
![image](https://cloud.githubusercontent.com/assets/325813/24116957/ffe84cc6-0d6d-11e7-8afd-c2823e3944ab.png)
