### ISSUE TITLE
Table name information and Table attribute information endpoints do not match what is available in Search endpoint

### ISSUE THREAD

**Issue by dstone42** [agrc/api.mapserv.utah.gov#441]
I have been using this API. It's a great tool. However, the information from the Table name information endpoint and the Table attribute information endpoint do not seem to match what is actually available for querying in the Search endpoint. For example, this request:
```
response = requests.get("http://api.mapserv.utah.gov/api/v1/info/featureClassNames?apikey=mykey&sgidCategory=location")
```
returns:
```
{'result': ['location.address_points',  
'location.address_system_quadrants',  
'location.buildings',  
'location.city_and_town_locations',  
'location.gnis_place_names',  
'location.hexagon_grid_1km',  
'location.luca_block_address_counts_2017',  
'location.zip_code_po_boxes',  
'location.zoom_locations'], 'status': 200}
```
How I understood this request is that these are tables in the location category. So, I do this request to find the fields of this table:
```
response = requests.get("http://api.mapserv.utah.gov/api/v1/info/fieldnames/address_points?apikey=mykey")
```
And I get this:
```
{'result': ['addnum',  
'addnumsuffix',  
'addsource',  
'addsystem',  
'building',  
'city',  
'countyid',  
'fulladd',  
'landmarkname',  
'loaddate',  
'parcelid',  
'prefixdir',  
'ptlocation',  
'pttype',  
'shape',  
'state',  
'streetname',  
'streettype',  
'structure',  
'suffixdir',  
'unitid',  
'unittype',  
'usng',  
'utaddptid', 
 'xid',  
'zipcode'], 'status': 200}
```
I understood that that meant that location.address_points is a table that I can search from and it has those columns. So, I tried this query:
```
response = requests.get("http://api.mapserv.utah.gov/api/v1/search/location.address_points/addnum,addnumsuffix,addsource,addsystem,building,city,countyid,fulladd,landmarkname,loaddate,parcelid,prefixdir,ptlocation,pttype,state,streetname,streettype,structure,suffixdir,unitid,unittype,usng,utaddptid,xid,zipcode?apikey=mykey")
```
And I get:
```
{'status': 400, 'message': 'The table `location.address_points` might not exist. Check your spelling.'}
```
I thought maybe it's like the table attributes endpoint and I need to remove the "location." part, so I tried the same query with the table name as "address_points" alone, but I get this:
```
{'status': 400, 'message': 'The table `address_points` does not exist in the Open SGID.'}
```
Can you explain why this table is said to exist by your API meta data, but it actually does not exist? I understand I may just be querying incorrectly, so I would appreciate it if someone can help me understand how to write this query better.
However, I believe that I'm setting up the query correctly because I tested a couple other tables that I can correctly query using this same setup of url (for example: location.gnis_place_names and location.zoom_locations).

Additionally, I want to share my greater goal in this in case anyone might be able to point me directly to the table/endpoint I need. I work at a hospital and we have a dataset listing the partners we interact with. We want to automatically create maps to show those partners, but we don't have their latitude or longitude. On top of that, we don't have their addresses. I have used a free geocoder called Nominatim to try geocoding these partners by their organization name, city, and state alone, but less than 25% of them are geocoded. I was hoping that in your database, you might have some information that would help me get the address, or better yet, the latitude and longitude of these partners I haven't been able to geocode.

**Comment by steveoh** [comment]
Thanks for creating this issue :tada:. 

I'm not sure what's going on in your example. One issue may be that the query without a predicate will attempt to return every address point, which is well over 500MB of data) in the SGID. If you need all that data, the API is not the right tool. But your error message does not match this.

I was able to take your query and add a predicate to limit the results to the city of tabiona and it completed successfully.

```
https://api.mapserv.utah.gov/api/v1/search/location.address_points/addnum,addnumsuffix,addsource,addsystem,building,city,countyid,fulladd,landmarkname,loaddate,parcelid,prefixdir,ptlocation,pttype,state,streetname,streettype,structure,suffixdir,unitid,unittype,usng,utaddptid,xid,zipcode?predicate=city=%27TABIONA%27&apikey=key
```

Is there something else going on that could be causing the url to be modified?

**Comment by dstone42** [comment]
True, my error message doesn't match that, but I'm guessing that's what's going on because I copied your url you just shared, and the request did work. I think maybe it's just a bad error message. 

The reason I didn't have a predicate is because I pulled the entire gnis_place_names and city_and_town_locations tables, so I assumed I could do the same thing for the other tables as well. I didn't really think through they might be vastly different in size. I mean I assumed there were size differences, but I didn't know how big those differences would be.

I was just pulling the whole thing because I couldn't really find good definitions of what's contained in each table and what all of the field names mean, so I was mostly trying to get an idea of what's in each table, and if any of them will help me solve my problem. I probably wasn't going about it the best way, but it's sometimes hard to think of a good predicate when I don't have a solid idea of what's in the table. I guess I was just being a bit lazy by pulling the whole thing, and dumping it into a file, so I can just ctrl-F and search for what I'm looking for.

However, if there's a table I decide I want to use, I might want to pull the whole thing. You mentioned the API is not the best tool for this. What is the best tool for pulling a whole table if I decide to do that?

**Comment by stdavis** [comment]
Hey @dstone42 

Here is a link to a service that provides the same address point data that our search api does: https://opendata.gis.utah.gov/datasets/utah::utah-address-points/about

You should be able to browse the data in the table directly in that website or you may download it in a variety of formats. You can search for or browser all of our data here: https://opendata.gis.utah.gov/

**Comment by dstone42** [comment]
Thanks! That's very helpful! You've answered my question, but I'm wondering if you might know one more thing. Assuming I do find what I'm looking for in your data, do you know if Idaho, Montana, Nevada, or Wyoming have similar resources?

**Comment by stdavis** [comment]
I'm not as familiar with what other states are up to. Here's something from another member of our team for Idaho: https://gis-idaho.hub.arcgis.com/

**Comment by dstone42** [comment]
Okay, I do have another question, but it's related more to the masquerade repo, so should I close this one and ask my question there? I will type my question in here, but if you want me to open an issue in that repo, I'll go there and open it, or you can just respond here if you know.

My end goal is to try and geocode a bunch of organizations that I don't have addresses for. I only have organization name, city, and state. I looked through all the tables at https://opendata.gis.utah.gov/, and none of them had information on the organizations I'm trying to geocode. I was looking through your other tools to see if any of them would be able to help me. 

I found the Masquerade service, and I'm wondering if it might be able to help me. I don't know if I totally understand it though. Is it using ArcGIS data, or is it still just accessing all the same data available through your API, but using an ArcGIS-like url format? The reason I ask is that github has a link to https://utah.maps.arcgis.com/apps/mapviewer/index.html. I was assuming the same data that's being used in this map viewer application is available on the API, but now I'm wondering if that might not be true.

An example of one of my organizations I'm trying to geocode that isn't working is "Confederated Tribes of the Goshute Reservation". When I go to the map viewer and type in that organization name, it pulls up the correct location. However, I have tried a few ways of trying to get information about this location from the masquerade API, but it's not coming up. Are there different data sources available in the map viewer than there are in the API?

Here are some example queries (this is in python, so it's fixing spaces and such for me):

https://masquerade.ugrc.utah.gov/arcgis/rest/services/UtahLocator/GeocodeServer/geocodeAddresses?addresses=Confederated Tribes of the Goshute Reservation&f=json
response: <!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n

https://masquerade.ugrc.utah.gov/arcgis/rest/services/UtahLocator/GeocodeServer/suggest?text=Confederated Tribes of the Goshute Reservation&f=json
response: {'status': 200, 'suggestions': []}

https://masquerade.ugrc.utah.gov/arcgis/rest/services/UtahLocator/GeocodeServer/findAddressCandidates?address=confederated tribes of the goshute reservation&city=Ibapah&region=Utah&f=json
response: {'candidates': [], 'spatialReference': {'latestWkid': 4326, 'wkid': 4326}, 'status': 200}


I also tested these endpoints with an organization that I successfully geocoded with the free service I tried previously: "Blue Mountain Hospital". Here is what I got for those requests:
geocodeAddresses endpoint: same error as the other one. Makes me think I probably am not putting that url together correctly.
suggest endpoint: I get a suggestion for Blue Mountain Hospital, and the id that came through made it look like it's from your system which is why I'm asking if the data from this API is the same as the other API.
findAddressCandidates: It also had a successful response, but no candidates. I don't know what's up with this endpoint. It might be more address focused, so it wouldn't catch an organization name like some other endpoints can. I don't know.

Anyway, you have more than answered my original question, so I'm sorry for dragging this issue out for longer than it needed to go. If this question is better answered in a new issue in the masquerade repo, you can close this one, and I'll open a new issue there to discuss this question. Sorry I have such a weird use case.

**Comment by stdavis** [comment]
I don't think that Masquerade can geocode these types of organizations at the moment. The results that you are seeing in the map viewer are coming from an [Esri World Geocoding Service](https://www.arcgis.com/home/item.html?id=305f2e55e67f4389bef269669fc2e284). You can check out [their docs](https://developers.arcgis.com/documentation/mapping-and-location-services/geocoding/) (this is a private vendor) for how to use this service.

**Comment by dstone42** [comment]
Okay, thanks! You have gone above and beyond to answer all my questions.
