### ISSUE TITLE
Quality Control Geocode Issues

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#45]
### Missing 33 S Haulage in Eureka in the address points

![image](https://cloud.githubusercontent.com/assets/325813/25405437/818b749c-29c0-11e7-9a7a-2c128d1e404b.png)

![image](https://cloud.githubusercontent.com/assets/325813/25405443/8cb7cb9a-29c0-11e7-9c1f-1f2c58c0fb42.png)

### Address range on 6639 W 3000 S, Roosevelt has some funky ranges. 

Geocoding on that address with the ACSALIAS gives 3 100% matches. The correct range is on the yellow dot on the right.

![image](https://cloud.githubusercontent.com/assets/325813/25411228/c52a51c4-29d8-11e7-9721-2cee8f959776.png)

**Comment by gregbunce** [comment]
good catch on the W 3000 S (SR 87) road segment.   Agreed, the ranges were funky.  I fixed them in UTRANS and they will be visible in the SGID roads after the next road update push (sometime in early June).  thanks for the feedback.  Zach is taking care of the 33 S Haulage in Eureka issue (adding the point).

**Comment by ZachBeck** [comment]
There is a 33 S Haulage point in the address points already, however, it's 150 meters south of the QC point you show above in red.
![33haulage](https://cloud.githubusercontent.com/assets/9662993/26461095/1819c7bc-4139-11e7-94a5-fb87dfff473f.jpg)

**Comment by steveoh** [comment]
Ok I will update the QC points. I suppose they weren't very well QC'd.

**Comment by steveoh** [comment]
@gregbunce it doesn't appear that the roosevelt address has gone into sgid yet. Is that true or is it still an issue?

**Comment by gregbunce** [comment]
It's fixed in UTRANS (back on May 25th).  It will be visible in SGID Roads on the next roads update - sometime next week.  My edits on those segments just missed the May roads update.  thanks for checking on it!

**Comment by steveoh** [comment]
Is the roosevelt change in SGID now @gregbunce?

**Comment by gregbunce** [comment]
@steveoh yup, I just verified, it's in SGID.  Close it out, baby!
