### ISSUE TITLE
arcgis online api key

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#49]
make this a first class citizen

**Comment by Tommyt43825** [comment]
I am looking forward to seeing if this is possible.   The ESRI World Geocoder is what I am currently using but it sure would be nice to have a geocoder just for the state of Utah to narrow the search results. Thanks and I will be following this thread.

**Comment by steveoh** [comment]
I researched this a bit this morning and started coding a solution when I realized that esri has modified the way arcgis.com address locating worked. The changes broke our existing geocoding solution and it doesn't appear that there is an acceptable work around.

**Comment by steveoh** [comment]
https://github.com/agrc/masquerade is the solution for this now.
