### ISSUE TITLE
buffer breaks new geometry query

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#50]
`THE POINT USED TO DO THE QUERY IS FOULED UP. CHECK THE SYNTAX POINT:[X,Y]"`

- [x] Also double check that the predicate is applied.

**Comment by steveoh** [comment]
turns out envelope's can't be casted to topological operators and therefore cannot be buffered.

**Comment by rschoenefeld** [comment]
Okay, makes sense. I'll use the envelope without a buffer then. Thank you.

**Comment by steveoh** [comment]
I updated the code to make envelopes polygons so buffer away my friend.

**Comment by rschoenefeld** [comment]
Yes, this works now. Thank you.
