### ISSUE TITLE
Midvale SLC Avenues

### ISSUE THREAD

**Issue by BGranberg** [agrc/api.mapserv.utah.gov#51]
If the address looks like midvale (zip or city) add a W if there's no prefix dir

If the address looks like Salt lake City (zip or city) add a E if there's no prefix dir (OR this could just be the default)

**Comment by steveoh** [comment]
@BGranberg 

midvale and 84047 address like

369 2nd ave
369 second ave
369 two ave

will now geocode. 

I'll fool on the slc avenues tomorrow.
