### ISSUE TITLE
650 S Flora Tech Rd, 84737 not being found

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#59]
@d-how says

Describe the problem you are having
We have the address 650 S Flora Tech Rd, 84737 and I found the API does not resolve the address correctly. The API returns a not found message. However, it does find 650 S Flora Tec Rd
, 84737 (Tech vs Tec). the street is actually Flora Tech not Flora Tec.

**Comment by steveoh** [comment]
@ZachBeck and @gregbunce would you check on the spelling of this address in the source data.

**Comment by steveoh** [comment]
I noticed that a road `650 S Flora Tech Rd` will not be found completely when the source data has the road as `Flora Tec`. I can misspell `Tec` and `Flora` other ways eg: `Florah Tec`, `Flora Tecs` and _still_ get a match with a lower score, but adding the `h` to `Tech` makes it not match at all. What gives?

This is not api logic, this is source data and locator logic.

**Comment by steveoh** [comment]
I can verify that it is indeed spelled wrong in the `roads` data.
![image](https://user-images.githubusercontent.com/325813/30709094-446d3bb8-9ebe-11e7-9ae6-99ac4d043d28.png)

We only have one `Flora Tech` address point along that segment.
![image](https://user-images.githubusercontent.com/325813/30709138-697cdce2-9ebe-11e7-8990-ac2bd827ca99.png)

**Comment by gregbunce** [comment]
Cool, yo.  I fixed it in the UTRANS roads data.  There were two segments that got updated.  This change will trickle through the system and be visible to all during the next roads update (mid to late Oct.).  If needed, I can force the change sooner (in SGID and RoadGrinder datasets), though I'd prefer not to.  

I don't have edit access to address points so - @ZachBeck can you update that address when you get a chance?  

gracias amigos. 

![image](https://user-images.githubusercontent.com/16906316/31150622-93ea66a6-a851-11e7-97ea-ab1bb1b07821.png)

**Comment by ZachBeck** [comment]
County fixed the road name on the address point on their end.
