### ISSUE TITLE
Elevation Service

### ISSUE THREAD

**Issue by stdavis** [agrc/api.mapserv.utah.gov#60]
I need a service that will give me data to make an elevation chart like this:
![image](https://user-images.githubusercontent.com/1326248/34587639-6035060a-f166-11e7-99aa-06bfe7e53db4.png)
for recreation.utah.gov.

I have been using a [service from Mapzen](https://mapzen.com/documentation/elevation/) but they are shutting it down on Feb 1st.

I know that @keatonwalker has code for building this type of data and experience with best practices.

**Comment by steveoh** [comment]
This would be built with c# arcobjects code. I'd love to hear @keatonwalker's opinions and I think this could be a cool addition to the web api. It's a bit specific and probably a bit processor intensive but pretty worthy none the less.

**Comment by stdavis** [comment]
Ya, I could see uses for roads as well.

I forgot to add that I'm working in a non-Esri environment so geojson or the [fancy google polyline encoding](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) would be best for me.

**Comment by stdavis** [comment]
I'm fine with a generic data type as well (similar to the point in the search api).

What do you need from me to get started on this? Would you like me to take a stab at defining the signature for this service?

**Comment by steveoh** [comment]
Sure that would be great

**Comment by keatonwalker** [comment]
Some of the longer trails could hit url limits if all the coordinates are listed in a get request. I could check the limits out further if we plan to use get as our method.

**Comment by steveoh** [comment]
this is definitely a post endpoint

**Comment by steveoh** [comment]
We should create a cache strategy as well since most requests will be duplicates

**Comment by stdavis** [comment]
I ended up [pre-generating the elevation profile data in the data for this app](https://github.com/agrc/TrailsAddin/blob/0a6a1ca8efabfd42d72112b25c69d7e4821969fe/ProProject/RoutesToolbox.pyt#L294-L315) so I no longer need this service. Not sure if you want to leave this open or not.

**Comment by steveoh** [comment]
Cool so you made a python tool or something to generate the elevations?
