### ISSUE TITLE
underscores in addresses

### ISSUE THREAD

**Issue by steveoh** [agrc/api.mapserv.utah.gov#62]
replace all `_` with ` `. People are geocoding addresses like `100_NORTH_348_EAST`

**Comment by stdavis** [comment]
Verified that "_" does **not** show up in the roads or address point data:
![image](https://user-images.githubusercontent.com/1326248/37829977-a68c0a12-2e66-11e8-8a16-99d16ef36867.png)
![image](https://user-images.githubusercontent.com/1326248/37829999-bf019f62-2e66-11e8-9e8e-25f5dfe0866f.png)
