### ISSUE TITLE
250 S Broadway, 84525 geocoding error

### ISSUE THREAD

**Issue by joshgroeneveld** [agrc/api.mapserv.utah.gov#64]
The Amtrak station in Green River gets misplaced on the geocoding API.  According to Amtrak, the address is `250 S Broadway, 84525` (this shows up the same in Google Maps).  _When I run this through the geocoding API, it gets translated to `250 N Broadway` that is several blocks away._

`http://api.mapserv.utah.gov/api/v1/geocode/250 S Broadway/84525?spatialReference=3857&format=geojson&apiKey=AGRC-Explorer`

![image](https://user-images.githubusercontent.com/4296780/39138598-8bcd4d50-46dd-11e8-8f17-f669d8912b3b.png)

When I search for the same address from the Emery County address site, it doesn't find `250 S Broadway`, but it does find `240 S Broadway` (which matches the address point feature class in the SGID).

![image](https://user-images.githubusercontent.com/4296780/39139202-8081c614-46de-11e8-892e-5a4411148db9.png)

Also, looking through the `SGID10.CADASTRE.Parcels_Emery` feature class, the address associated with this location is `55 W Green River Ave`

![image](https://user-images.githubusercontent.com/4296780/39138865-f21682c0-46dd-11e8-8325-dc93c9997d7b.png)

I'm not sure which address is correct, but thought you'd want to know that the address from the Amtrak website doesn't resolve to the station location.

**Comment by steveoh** [comment]
I will close this for now, but after the next roads update let's check this. Greg can this be on the list of "new" addresses to check after the next roads update?

**Comment by gregbunce** [comment]
Just a follow-up, this address now codes.
