### ISSUE TITLE
Can create api key before confirming account

### ISSUE THREAD

**Issue by sitlaBarry** [agrc/api.mapserv.utah.gov#66]
Kate (katestaley@utah.gov) created an account but didn't notice she was supposed to confirm her account.  She created an api key and started using it in her code, but was getting an error along the lines of "invalid api key," which makes sense since it was a non confirmed account.  It seems like you should get an error when you try to create a key without first confirming.

**Comment by steveoh** [comment]
Thanks Barry!

This was a calculated decision. We want people to sign up, create keys, and get that out of the way without worrying about any account stuff. They will be more invested by the time they realize they need to do other stuff to continue.

The response [tells the user exactly what is wrong](https://github.com/agrc/api.mapserv.utah.gov/blob/master/WebAPI.API/Handlers/Delegating/AuthorizeRequestHandler.cs#L118-L126) so they should not have a hard time figuring that out. 

I think the enhancement here is to pop a warning when a person creates a key with an unconfirmed email, with text that it cannot be used until email confirmation happens.

What do you think about that?

**Comment by sitlaBarry** [comment]
You're right, the message is explicit (you guys should give ESRI some lessons,) but it would be good to be more clear up front. I think your solution would be perfect.

**Comment by steveoh** [comment]
we no longer confirm accounts. that is a utahid concern now.
