### ISSUE TITLE
"Route and Milepost" API should use Full Route Name, currently returns incorrect result

### ISSUE THREAD

**Issue by clancyblack** [agrc/api.mapserv.utah.gov#83]
The Route and Milepost API should require the Full Route Name. Currently it seems to return the first matching route name, including ramps.

To reproduce:
Enter Route=0015P, milepost=1.1, side=(any). This will return a result on a collector ramp in Salt Lake County. The Full Route Name of this collector ramp is actually 0015PC######. If you change the input milepost to 1.9 it now returns a result in St. George. The API as designed is giving incorrect results because you may get a ramp result once and a mainline result another time. Needs to use the full route name in order to give predictable results.

FYI we are using this API for a UDOT application and found this issue. We would greatly appreciate a fix.

Thanks,
Clancy Black
clancyblack@utah.gov

**Comment by clancyblack** [comment]
The most precise method would be to use the full route name for the "route" input. That would eliminate the need for the "side" input as well.

The full route name is 4 digits (with leading zeros) plus a P or N for highways. The P (increasing) and the N (descreasing) give the "side" info that is currently asked for separately. 

Ramps and collectors also have a R or C for Ramp or Collector, followed by a 3-digit number representing the exit number, followed by a 2-digit number representing the ramp number. (example: 0015PC30554).

For comparison, the Reverse Route and Milepost API already returns the full route name. Input x=-111.90405234070917 and y=40.73647265310341 and include ramps, you should get a route returned of "15PC30554". UDOT would have two leading zeros as well, but that represents the full route name.

Hopefully that makes sense, if for some reason this option doesn't work I'm happy to talk about other ideas.

**Comment by steveoh** [comment]
The most precise method sounds ok. Unfortunately, it would be a breaking change to v1 clients and cannot be done -- even though it _could_ be returning incorrect/unexpected results. Although, after writing that, I may change my mind. I'll need to talk to some others in the office to get their opinions. 🤔 

What we can certainly do in a v1 enhancement, is add more properties to the request to make the request more precise. These would be opt-in properties that would default to the original functionality as it is currently.

I do not like the idea of requiring leading zeros for routes as that is a data storage concern that people shouldn't need to understand. If a client wants `I-15` they shouldn't have to know to pad `15` with some amount of zeros. It is very unintuitive unless you are very familiar with the data. :-1:

I can see adding `includeRamps` and `includeCollectors` as a boolean to limit the result to mainlines, ramps, or collectors. Although that would not allow a client to specifically find a ramp or collector. The endpoint would need to accept an exit number and ramp number also.

What are your thoughts?



This might be worth making the default in version 2 but the release date for the version 2 api is still

**Comment by clancyblack** [comment]
That all makes total sense, sorry if my explanation was overwhelming, just wanted to give you all the details. I totally get that we have to keep v1 working as-is.

You're right, we can include/exclude ramps/collectors but the existing version would still potentially give an unexpected result. In general the ideas you suggest would work I think. I provide another suggestion below.

What if there was a boolean "usefullroute" that is false by default, allowing existing users to continue without interruption. If true, the API would look for the full route name instead of just the number. This only creates one new input because you can use the existing route input. Users like us that need to differentiate would mark usefullroute as true and give the full route name. This is kind of like building v2 inside v1.

Not sure if that's practical, just an idea.

**Comment by steveoh** [comment]
I think that is a decent compromise. I am still uncertain what that v2 signature will look like, but I think this could work for v1.

**Comment by clancyblack** [comment]
Steve,

Don't mean to bug you because we're so grateful for the other change you
already made, but I'm curious if this change is still on the table. Any
update?

Thanks

WCEC Engineers
UDOT Consultant
801-722-9736

**Comment by steveoh** [comment]
No problem. We are in a bit of a funding crunch right now so I've had to switch to paid work. If you want to sponsor this feature, we could make it happen sooner.

cc @brigsz

**Comment by clancyblack** [comment]
Makes sense, I'm not sure of how that works but I will ask our group. If
you have any info/explanation of that process it would help.

Clancy

WCEC Engineers
UDOT Consultant
801-722-9736
