### ISSUE TITLE
Feature Request for "Reverse Route and Milepost" API

### ISSUE THREAD

**Issue by clancyblack** [agrc/api.mapserv.utah.gov#84]
We are using the "Reverse Route and Milepost" API for a UDOT application for project planning and program management. As part of this we are using this API to allow users to drop a pin and have forms automatically fill in the route/milepoint for them. This is an issue when the location is an intersection because the API returns the nearest result, often giving the user a route they weren't expecting.

Our request is to add a True/False input condition for "Return All" that, if True, would return all results within the buffer area rather than only the nearest result. This would allow us to show the user both results at the intersection and give them the chance to choose which route they wanted. This condition could be False by default in order to not cause issues for people that may already be using the API.

Thanks for considering this,
Clancy Black
clancyblack@utah.gov

**Comment by clancyblack** [comment]
That would be great, yes let me know how I can help.

**Comment by steveoh** [comment]
@clancyblack I've started to implement something for this. The api response format is a bit interesting. With the format

```json
 "TopResult": { },
 "EqualCandidates": [ ]
}
```

I've added a `CandidatesNearby` property to include the other results. Would you give me an input x,y with all the parameters and the expected result from the api so I can determine if this will suite your needs?

**Comment by clancyblack** [comment]
This sounds great. Here are two examples you could test:

X: -111.890836
Y: 40.588079
Ramp: true
Buffer: blank
Ref: 4326
RESULT: Should return route 209P about milepoint 12.18 and route 89P about milepoint 366.8

X: -111.685057
Y: 40.234105
Ramp: true
Buffer: blank
Ref: 4326
RESULT (4): 14P mp 1.06, 15P mp 265.6, 15N mp 265.6, 15PR26509 mp 0.034

Thanks

**Comment by steveoh** [comment]
@clancyblack Let me know what you think about these results?

## Sample 1

sample response

```json

 "result": {
  "route": "209P",
  "offsetMeters": 1.55,
  "milepost": 12.184,
  "side": "increasing",
  "candidates": [
   {
    "route": "89P",
    "offsetMeters": 5.37,
    "milepost": 366.796,
    "side": "increasing"
   }
  ]
 },
 "status": 200
}
```

## Sample 2

samplem response

```json
{
 "result": {
  "route": "15PR26509",
  "offsetMeters": 2.05,
  "milepost": 0.034,
  "side": "increasing",
  "candidates": [
   {
    "route": "15PR26502",
    "offsetMeters": 52.69,
    "milepost": 0,
    "side": "decreasing"
   },
   {
    "route": "15NR26503",
    "offsetMeters": 65.28,
    "milepost": 0.174,
    "side": "decreasing"
   },
   {
    "route": "15NR26508",
    "offsetMeters": 62.7,
    "milepost": 0.026,
    "side": "decreasing"
   },
   {
    "route": "15NR26507",
    "offsetMeters": 47.95,
    "milepost": 0.008,
    "side": "decreasing"
   },
   {
    "route": "114P",
    "offsetMeters": 19.01,
    "milepost": 1.058,
    "side": "decreasing"
   },
   {
    "route": "15N",
    "offsetMeters": 9.79,
    "milepost": 265.623,
    "side": "increasing"
   },
   {
    "route": "15P",
    "offsetMeters": 11.81,
    "milepost": 265.623,
    "side": "decreasing"
   }
  ]
 },
 "status": 200
}
```

**Comment by clancyblack** [comment]
Those look great. The second one returned a lot more results than, but that doesn't surprise me given how many ramps are in that area. It looks like it is working exactly how I would expect. This will be extremely helpful for how we are using the service.

**Comment by steveoh** [comment]
I am going to order the results by `offsetmeters` and add a `suggestion` property to let you cap the `candidate` count and then deploy it.

**Comment by clancyblack** [comment]
Sounds great, thanks again!

WCEC Engineers
UDOT Consultant
801-722-9736

**Comment by steveoh** [comment]
this is now live in v1.10. Please test and provide any feedback

**Comment by clancyblack** [comment]
Thanks Steve. I ran a few tests on the live api and it looks good. We're
integrating this into our systems in about a month, we'll let you know how
it goes.

Clancy

WCEC Engineers
UDOT Consultant
801-722-9736
