### ISSUE TITLE
Geocoding API Explorer shows HTTPS, but only works with HTTP

### ISSUE THREAD

**Issue by joshgroeneveld** [agrc/api.mapserv.utah.gov#88]
In the Web API Explorer, it shows a URL with HTTPS when geocoding with street and zone:
![image](https://user-images.githubusercontent.com/4296780/52647380-d6cecc00-2ea1-11e9-9059-70812e08913b.png)
If I try the same address using the Python requests library, I get an error if I use https:
![image](https://user-images.githubusercontent.com/4296780/52647965-e69ae000-2ea2-11e9-9cec-9de81d4fd5c4.png)
If I change the URL to http instead of https, it works:
![image](https://user-images.githubusercontent.com/4296780/52648166-472a1d00-2ea3-11e9-9ede-37d682fbbfca.png)
The http URL matches what you have showing in the Python geocoding samples:
https://github.com/agrc/GeocodingSample/blob/master/Python/Geocoding.py

I read your blog post on the upcoming V2 of the Web API, but I didn't see anything there about HTTPS for geocoding (maybe I missed it?).
https://gis.utah.gov/the-next-agrc-web-api/

I'm happy that the HTTP URL works, but just confused that the Web API Explorer shows an HTTPS URL that doesn't work.

**Comment by steveoh** [comment]
Https definitely works. I think the error is in the python code and the sample probably needs to be updated to be successful with https. I would start investigating making https requests with python. I am going to close this and open an issue to update the sample code. Thanks @joshgroeneveld

**Comment by steveoh** [comment]
Follow along in #89
