### ISSUE TITLE
"Same" address, different results

### ISSUE THREAD

**Issue by sterlingpetersen** [agrc/api.mapserv.utah.gov#93]
Ran across these two addresses resolving to different points. Probably OK for many use cases (maybe close enough), but I wondered if this should be captured with some backend street aliasing or whatnot.

```
{
 "addresses": [
  {
   "id": 1,
   "street": "2075 N 1200 W",
   "zone": "84041"
  },
{
   "id": 2,
   "street": "2075 UNIVERSITY PARK BLVD",
   "zone": "84041"
  }
 ]
}
```

**Comment by steveoh** [comment]
I will assume one is going to the address points and the other the centerlines?

**Comment by steveoh** [comment]
verified. @gregbunce does the road grinder not create alias records for the address points?

**Comment by gregbunce** [comment]
So, only the sgid roads contain alias names - address points in the sgid do not.  however, we do run the address points through the roadgrinder optimization process where we create an alternate names table for them if they can be geocoded without a predir.   My guess on issue #93 would be the same as @steveoh  which is possible - one dataset is using the primary address and the other is using the alias.  it's one of the projects we are working on at AGRC - to run cross-check to ensure they are both using the primary address.  thanks for pointing this out.

**Comment by steveoh** [comment]
Correct me if I make any incorrect assumptions based on your reply @gregbunce...

> one dataset is using the primary address and the other is using the alias.

You are saying that the address points only use the primary address, while the centerlines have an alt names table built in road grinder that allows them to use the alias fields.

To further clarify, road grinder is only creating the alt names table without predirs for the address point locator.

If that is all accurate, how much work would you estimate to use the primary address on the address points to enhance the alt names table using the aliases from the roads? Is it feasible? Would it be accurate? Is there prerequisite work to be done to achieve this? Can you think of any reasons not to do this?

**Comment by gregbunce** [comment]
Yup, address points only contain the primary address name.  whereas the roads dataset contains both a primary and an alias road name.  

For the road grinder data, an alternate names table is created for both datasets.  

For the roads the alternate names table: it contains the alias names as well as a record if you don't need a predir on the primary.  

For the address points alternate names table: it contains address point records that don't need a predir.

regarding your question.  I'll have to think about it a bit.  I'll have to dive into the data and think about how address ranges on the road alias names factor into this.  It would definitely take some time.  However, I think it is something to think about.  let me talk to zach about how alias addressing is handled on address points - if at all.

**Comment by gregbunce** [comment]
A little more info on issue #93.  It looks like the primary address name for this location is University Park.  The roads dataset has University Park as the primary and 1200 W as the alias.  The address point dataset has two points stacked on top of each other - one with Univerity Park, the other with 1200 W.   I suppose both addresses are valid for this location.

**Comment by steveoh** [comment]
2075 UNIVERSITY PARK BLVD matches on centerlines.

**Comment by steveoh** [comment]
@sterlingpetersen It looks like you are using the multiple address geocoding endpoint. I am going to mark that as deprecated. I would suggest updating your code to use the single address endpoint while we sort out this issue. Thanks!

**Comment by gregbunce** [comment]
I will work with @ZachBeck to resolve the mismatch in address points and roads for the address: 2075 University Park Blvd in Layton.  Essentially, the address points are missing the word "Park" in the street name.  When looking on google street view, the street name is "University Park Blvd".

**Comment by ZachBeck** [comment]
University Park Blvd addresses are fixed in the address points now.

**Comment by steveoh** [comment]
/remind me to verify that `2075 N 1200 W, 84041` and 2075 `UNIVERSITY PARK BLVD, 84041` return the same location 8/10

**Comment by steveoh** [comment]
this looks good now
![image](https://user-images.githubusercontent.com/325813/89809755-3f2f5580-daf9-11ea-89c9-e85910852728.png)
![image](https://user-images.githubusercontent.com/325813/89809786-4b1b1780-daf9-11ea-9b63-2e9f49b60b1a.png)
