### ISSUE TITLE
Reverse Route and Milepost not handling Federal Aid Routes

### ISSUE THREAD

**Issue by clancyblack** [agrc/api.mapserv.utah.gov#96]
The "Reverse Route and Milepost" API does not seem to handle Federal Aid routes even if the includeRampSystem parameter is set to True.

Reproduce:
Using the "Route and Milepost" API input a federal aid route and associated parameters. For example, route = 2960P, milepost = 1.007, spatial ref = 4326, and fullroute = true. This should return a x/y of 
"x": -111.71475729348826,
   "y": 40.29718315950986

Then, input these x/y coordinate into the "Reverse Route and Milepost" API along with includeRampSystem = true and spatialref = 4326. The API will return 
{
 "status": 404,
 "message": "No milepost was found within your buffer radius."
}

Expected behavior is that it returns the same route and mp input in the Route and Milepost API.

**Comment by steveoh** [comment]
Right now the reverse milepost doesn't include the [federal aid routes](https://github.com/agrc/api.mapserv.utah.gov/blob/master/WebAPI.Search.Soe/Endpoints/ReverseMilepost.cs#L170), collectors, or ramps. I'm not sure why we made that decision. It sounds like we should include at least the federal aid routes.

We are updating the code to give the option to use the new UDOT roads and highways services. This may solve this issue in the future.

**Comment by steveoh** [comment]
Handled by UDOT roads and highways
